### ISSUE TITLE
How to get all users repos

### ISSUE THREAD

**Issue by schmittyjd** [elwayman02/ember-data-github#102]
I am newer to ember and I am trying to figure out how i can get access to all of my repositories through this ember data adapter. So far i am able to get ahold of my user data (and get authenticated) like so
```js
// in /routes/profile/index.js
Ember.Route.extend({
  model() {
    return this.get('store').findRecord('github-user', '#');
  }
});
```
And then in my repos route (where i plan to show a list of repos)
```js
// in routes/profile/repos.js

Ember.Route.extend({
  model() {
    const user = this.get('store').findRecord('github-user', '#');
    let repos = user.githubRepositories;

    return repos;
  }
});
```

Now I understand that `user.githubRepositories` will return an ember `DS.PromiseManyArray` promise, but I do not understand what type of promise code to use to actually get a hand on the repository data.

Any help would be appreciated, thanks!

**Comment by elwayman02** [comment]
Try this

```
model() {
  this.get('store').findRecord('github-user', '#').then((user) => {
    return user.githubRepositories;
  });
}
```

**Comment by schmittyjd** [comment]
Awesome thanks for the quick reply! looks like that is working. I also found out too that if I just mess with the base user object in the templates I can loop through my repos doing something like
```handlebars
{{#each model.githubRepositories as |repo|}}
{{repo.name}}
{{/each}}
```

Awesome!
