### ISSUE TITLE
Consider renaming user property on release model to author

### ISSUE THREAD

**Issue by Dhaulagiri** [elwayman02/ember-data-github#113]
The name of the property in this addon is `user` but in the actual [github payload](https://developer.github.com/v3/repos/releases/#response) it is referred to as `author`. 

https://github.com/elwayman02/ember-data-github/blob/0989d8b2983be3c6d7bee400a6ac77ec3c52e254/addon/models/github-release.js#L19

**Comment by elwayman02** [comment]
I agree, author seems better here.
