### ISSUE TITLE
Yarn changelog doesn't seem to do anything

### ISSUE THREAD

**Issue by elwayman02** [elwayman02/ember-data-github#157]
@Dhaulagiri I'm not sure what I'm doing wrong, but running `yarn changelog` after pulling an unreleased version of master did not update the changelog with the latest commits.

**Comment by elwayman02** [comment]
I did that, lerna actually threw an error until I fixed that. Now the script runs and completes without error, but produces no output.

**Comment by Dhaulagiri** [comment]
See my comment in #158, but I believe https://github.com/elwayman02/ember-data-github/issues/156 will fix this
