### ISSUE TITLE
Adding `commit` to the `github-branch` serializer

### ISSUE THREAD

**Issue by raulb** [elwayman02/ember-data-github#68]
Hi @elwayman02!

I wanted to hear your thoughts in regards to something before I go ahead and open a PR.

I just started using your addon because I needed to fetch the information for GitHub branches, but among the name, I wanted to show also the latest commit message. Since I don't need to create a separate `Commit` model for now, what I'm doing is the following:

```js
// ember-data-github/addon/serializers/github-branch.js

import GithubSerializer from './github';

export default GithubSerializer.extend({
  normalize(type, hash, prop) {
    hash = {
      id: hash.recordId || hash.commit.url.replace('https://api.github.com/repos/', '').replace(/\/commits\/.+/, `/branches/${hash.name}`),
      name: hash.name,
      commit: hash.commit
    };
    return this._super(type, hash, prop);
  }
});
```

```js
// ember-data-github/addon/models/github-branch.js

import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  commit: DS.attr()
});
```

Is there a reason not to do that, or did you have in mind leaving the option for creating a separate model for Commits?

Thanks!

**Comment by elwayman02** [comment]
If Commit is an object with a unique ID, it almost definitely should have its own model,so that we can keep proper relationships between the objects. If not, it's OK to take the shortcut of treating it as a blob, albeit a bit hacky.

**Comment by raulb** [comment]
@elwayman02 yeah, it contains its `sha`, ergo we could use that as an id as a separate model. I think it makes sense 👍
