### ISSUE TITLE
Make default user token configurable

### ISSUE THREAD

**Issue by srvance** [elwayman02/ember-data-github#75]
Wanted to see what you thought of this before I implement it. Using `#` as the token to indicate the default user makes it impossible to declare a route that passes that token because `#` has special meaning in URLs. Making the token configurable would let you redefine it in a declarative way that could work with URLs.

```
http://localhost:4200/user/elwayman02  // Standard usage with dynamic segment
http://localhost:4200/user/#  // Doesn't work because hashes have special meaning in URLs
http://localhost:4200/user/-  // Works for the URL, but requires additional route declaration
```

I propose a configuration parameter `ENV['ember-data-github'].defaultUserToken` that would be used if specified with `#` as the default.

**Comment by srvance** [comment]
Instead of the literal `#` [here](https://github.com/elwayman02/ember-data-github/blob/master/addon/adapters/github-user.js#L6), reference a config parameter.

**Comment by elwayman02** [comment]
Thanks, that seems reasonable. Go for it!

**Comment by srvance** [comment]
Questioning my own suggestion, the translation could happen in the route itself if needed. I've ended up avoiding the situation that motivated this through judicious use of nested and index routes. Still think it's a good idea?

**Comment by elwayman02** [comment]
Hmm, if it's something that won't come up if routes are well-defined, then I'm ok with not making configuration over-complicated by adding this.

**Comment by srvance** [comment]
I'll close this, then.
