### ISSUE TITLE
Design to support GitHub Trees API

### ISSUE THREAD

**Issue by srvance** [elwayman02/ember-data-github#77]
I decided to use the [Tree API](https://developer.github.com/v3/git/trees/) rather than the [Contents API](https://developer.github.com/v3/repos/contents/) to navigate the file tree in the repo. It's more concise in its response and seems to have fewer limits on its responses.

It's return is like

```json
{
  "sha": "9fb037999f264ba9a7fc6274d15fa3ae2ab98312",
  "url": "https://api.github.com/repos/octocat/Hello-World/trees/9fb037999f264ba9a7fc6274d15fa3ae2ab98312",
  "tree": [
    {
      "path": "file.rb",
      "mode": "100644",
      "type": "blob",
      "size": 30,
      "sha": "44b4fc6d56897b048c772eb4087f854f46256132",
      "url": "https://api.github.com/repos/octocat/Hello-World/git/blobs/44b4fc6d56897b048c772eb4087f854f46256132"
    },
    {
      "path": "subdir",
      "mode": "040000",
      "type": "tree",
      "sha": "f484d249c660418515fb01c2b9662073663c242e",
      "url": "https://api.github.com/repos/octocat/Hello-World/git/blobs/f484d249c660418515fb01c2b9662073663c242e"
    },
    {
      "path": "exec_file",
      "mode": "100755",
      "type": "blob",
      "size": 75,
      "sha": "45b983be36b73c0788dc9cbcb76cbb80fc7bb057",
      "url": "https://api.github.com/repos/octocat/Hello-World/git/blobs/45b983be36b73c0788dc9cbcb76cbb80fc7bb057"
    }
  ],
  "truncated": false
}
```

I think it's clear that the `id` needs to be the SHA, even if it could cause some doubling of the model at the entry point when using something like a branch name instead of a SHA, e.g., `https://api.github.com/repos/elwayman02/ember-data-github/git/trees/master`.

I'm not sure how to model the `tree` array and its contents. They could be sorted into `blob`s and `tree`s, although that may be better done as CPs. They have a relationship to other types but those types don't have the same representation as the data contained in the array. Something like [ember-data-model-fragments](https://github.com/lytics/ember-data-model-fragments) might be appropriate.

Thoughts?

**Comment by elwayman02** [comment]
Are the shas in the `tree` array not unique? Could we not use those as ids?

**Comment by srvance** [comment]
They are. Those would be ids. But the data content for tree items is different than the data content when the item is the root of the tree.

**Comment by elwayman02** [comment]
It looks like the only difference is an added `size` attr for blobs...are there additional variations in the data structure of those items?

**Comment by srvance** [comment]
You don't have `path`, `type`, or `mode` at the top level for the tree that was queried. I don't care about `mode` for my purposes, but the others are essential.

**Comment by srvance** [comment]
I'm starting to think the Contents API may be cleaner for my purposes, after all. I just need to figure out polymorphic models.

**Comment by elwayman02** [comment]
Should we keep this issue open or close it?
