### ISSUE TITLE
Ember 2.x

### ISSUE THREAD

**Issue by elwayman02** [elwayman02/ember-data-github#9]
Any plans to update this to Ember 2.x and Ember-Data 2.x?

**Comment by jimmay5469** [comment]
Unfortunately I don't have any plans to do it myself, although I don't believe it would be too hard to update.

**Comment by elwayman02** [comment]
@jimmay5469 I saw your note about no longer maintaining this addon; I'd be happy to transfer ownership and take a crack at it at some point, if you want.

**Comment by jimmay5469** [comment]
Yeah, that would be great! Are you on the ember community slack? I am jimmay5469 on there, we could use that to communicate the details for getting things transferred. I think the addon is a cool idea and it would be awesome to see it developed further. I ended up losing interest in the side project I was using the addon for so I stopped actively working on the addon.
